version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./applications/backend/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - variant_app_network

networks:
  variant_app_network:
    external: true
